### ISSUE TITLE
Client example in Rust

### ISSUE THREAD

**Issue by wisespace-io** [rickyhan/tectonicdb#14]
It would be nice to have an example showing how to use it with Rust. So I could use it to implement https://github.com/wisespace-io/binance-rs/issues/6

**Comment by rickyhan** [comment]
Hello, I have updated the docs and included a Rust cli example: http://rickyhan.com/tectonicdb/examples/example-rust-db.html

Just copy everything in this folder to your db directory: https://github.com/rickyhan/tectonicdb/tree/master/cli/rust
