### ISSUE TITLE
GET range problem: catch will return everything in memory if range not found

### ISSUE THREAD

**Issue by mingrui** [rickyhan/tectonicdb#28]
I have trouble understanding this line:

https://github.com/rickyhan/tectonicdb/blob/79b67d05182773a822d232c7cecfdfcb06c5374e/src/bin/server/state.rs#L561

I am trying to search for a timestamp range with `GET FROM x TO y`, in both memory and filestore. I see in the code that if range is not in memory, it will `return None`. But then `unwrap_to` catches the `None` and returns everything that's in memory. Is this the correct behavior?

I can of course work around this by doing `FLUSH` and `CLEAR ALL` before my get range query. But it's a bit convoluted.

Thank you!

**Comment by mingrui** [comment]
@Swoorup did you have a similar problem?

**Comment by Swoorup** [comment]
Just an off-topic and personal question, did you evaluate any other databases like postgres, before choosing tectonicdb? I am evaluating other databases as well due to missing features.

**Comment by mingrui** [comment]
> Just an off-topic and personal question, did you evaluate any other databases like postgres, before choosing tectonicdb? I am evaluating other databases as well due to missing features.

shoot me an email to discuss, thx!
mjray3691    aaatttt    gmail
