### ISSUE TITLE
Is it possible to store multiple tickers in one database?

### ISSUE THREAD

**Issue by ksanderer** [rickyhan/tectonicdb#3]
Can't figure out is it possible to store data from multiple sources? 

For example for example if I have streaming data from two platforms:
```
platform1:
    ETH/BTC
    ETH/USDT

platform2:
    ETH/BTC
    ETH/USDT
```
How can I handle this with tectonicdb?

**Comment by rickyhan** [comment]
Set the symbols to

pl1_eth_btc

platform_quote_base


This is how I do it but there are other ways too.

**Comment by ksanderer** [comment]
Probably I'm doing something wrong.

I'm using python wrapper from `cli/python/tectonic.py` like this:

```
tectonic = TectonicDB(port=4982)

tectonic.add(quote['timestamp'], quote['seq'], quote['is_trade'], quote['is_bid'], quote['price'], quote['size'])
```
Where should I place symbol?

-----
And one more question. In the code, there are few interesting methods to analyze the data (candlesticks for example). How can I use them (I'm using python in my app)?

**Comment by rickyhan** [comment]
I have edited Python client to support insertion.

Re: postprocessing: I will expose these functions later. For now you can read `dtf::Update` from file and apply these functions.
