### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by crackcomm** [rickyhan/tectonicdb#5]
Hello, I want to use `tectonicdb` and integrate it into my work which is [crypto-bank](https://github.com/crypto-bank/crypto-bank), I want to contribute as much as possible and not to split the codebases as much as it will be possible, are you up to a conversation about it on gitter or somewhere else?

Thank you

**Comment by rickyhan** [comment]
Hello could you send me an email please?

github@rickyhan.com
