### ISSUE TITLE
Javascript / Typescript api not working

### ISSUE THREAD

**Issue by Swoorup** [rickyhan/tectonicdb#7]
It seems that this does not work, since the `\n` was removed as the terminating response message.

**Comment by rickyhan** [comment]
These two commits should fix the js api.

https://github.com/rickyhan/tectonicdb/commit/94959feecc8e76bd82ca5cc3b69e6e12c53171d4

https://github.com/rickyhan/tectonicdb/commit/ce813a155d9827cc1a1cc965145ffad1663a3100
